### ISSUE TITLE
Counter that counts up?

### ISSUE THREAD

**Issue by tegk** [bakins/gearman-exporter#16]
Why not use a counter that counts up rather than to count the current jobs?

**Comment by zoonage** [comment]
@tegk  This functionality isn't possible as you cannot know if a job has completed by the time the second scrape has. If you have a scrape interval of 30 seconds but each job takes 1 minute then the job will be counted twice by a counter.

The counting would have to be done by Gearman.

**Comment by tegk** [comment]
> @tegk  This functionality isn't possible as you cannot know if a job has completed by the time the second scrape has. If you have a scrape interval of 30 seconds but each job takes 1 minute then the job will be counted twice by a counter.
> 
> The counting would have to be done by Gearman.

That's why you would always increment and let Prometheus calculate the rate

**Comment by zoonage** [comment]
> > @tegk  This functionality isn't possible as you cannot know if a job has completed by the time the second scrape has. If you have a scrape interval of 30 seconds but each job takes 1 minute then the job will be counted twice by a counter.
> > The counting would have to be done by Gearman.
> 
> That's why you would always increment and let Prometheus calculate the rate

The counter carries the risk of overcounting jobs, so the rate as calculated by Prometheus could appear higher than what it actually is
