### ISSUE TITLE
Add metric "status_waiting"

### ISSUE THREAD

**Issue by njam** [bakins/gearman-exporter#2]
What do you think about adding a derived metric `status_waiting`, which would be calculated as `status_total - status_running`. I usually find it very helpful for monitoring, because I want it always to be close to 0.

Thanks for this great program!
fyi I created a Dockerfile for it here: https://github.com/cargomedia/docker-gearman-exporter

**Comment by bakins** [comment]
@njam I no longer use gearman. I was using it for a small side project.  Do you want to take ownership of this project?

**Comment by njam** [comment]
I wish I could say the same ;)
I'd be happy to help out!
You could just give me write/admin permissions on the repo if you want.
